name: CI/CD to Cloud Run (OIDC)

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]   # solo cuando el PR se cierra (mergeado o no)

jobs:
  deploy:
    if: github.event.pull_request.merged == true   # solo si fue mergeado
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Auth via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push image
        run: |
          IMAGE_URI=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservicios/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}
          docker build -t $IMAGE_URI sendemail
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image $IMAGE_URI \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --cpu=1 --memory=512Mi --max-instances=1 \
            --set-env-vars MAIL_USER=${{ secrets.MAIL_USER }},MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }},EMAIL_DESTINATION=${{ vars.EMAIL_DESTINATION }} \
            --port 8080
